export const skills = [
  {
    name: "Languages (in order of proficiency)",
    items: [
      "TypeScript",
      "JavaScript",
      "Python",
      "C/C++",
      "Rust",
      "Go",
      "Java",
      "Bash",
      "Lua",
    ],
  },
  {
    name: "Frameworks & Libraries",
    items: [
      "React",
      "Next.js",
      "Express",
      "Hono",
      "Prisma",
      "Socket.IO",
      "Tailwind CSS",
      "Tokio",
      "Bun",
      "Flask",
      "Pyrogram",
      "Telethon",
    ],
  },
  {
    name: "AI Agents & Robotics",
    items: [
      "AI Coding Agents",
      "LLM Integration",
      "ROS 2",
      "MoveIt / MTC",
      "Motion Planning",
    ],
  },
  {
    name: "Blockchain",
    items: ["Solana", "Ethereum", "Anchor"],
  },
  {
    name: "Tools & Environment",
    items: [
      "Linux",
      "Neovim",
      "Docker",
      "Git",
      "Redis",
      "PostgreSQL",
      "MySQL",
      "MongoDB",
    ],
  },
  {
    name: "DevOps & Cloud",
    items: [
      "Nginx",
      "AWS EC2",
      "AWS ECS",
      "AWS Lambda",
      "AWS S3",
      "AWS ElastiCache",
      "AWS CloudWatch",
      "Cloudflare Workers",
      "Cloudflare R2",
      "Docker-CLI",
    ],
  },
];

